server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dian?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    minimum-idle: 5
    maximum-pool-size: 20
    max-lifetime: 1800000
    pool-name: dian
    idle-timeout: 30000
    connection-timeout: 30000
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.230.130
    port: 6379
    password: 123456
mybatis-plus:
